### ISSUE TITLE
Exception thrown while trying to calculate ``math.log(0)``

### ISSUE THREAD

**Issue by gnufede** [bloomberg/pytest-memray#102]
## Bug Report

**Current Behavior** 

``math.log(0)`` raises ``ValueError: math domain error``

**Expected behavior/code**

No exceptions raised while trying to calculate the log of a number too close to zero.

**Environment**

- Python(s): Any I guess

**Possible Solution**

```
low = math.log(low) if low > 5e-324 else -750
```

**Additional context/Screenshots**

https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/52341/workflows/776c836a-ea10-4af8-8154-236971fa72fc/jobs/3333537

**Comment by godlygeek** [comment]
Done in #103
