### ISSUE TITLE
incompatible with flaky (as used in urllib3)

### ISSUE THREAD

**Issue by graingert** [bloomberg/pytest-memray#53]
## Bug Report

**Current Behavior** if pytest-flaky re-runs a test it fails with `FAILED test/test_demo.py::test_demo - RuntimeError: No more than one Tracker instance can be active at the same time`

**Input Code**

```python
import itertools

import pytest

count = itertools.count().__next__

@pytest.mark.flaky
def test_demo():
    if count() <= 0:
        assert False
```

**Expected behavior/code**

**Environment**

- Python(s): all versions (tested on 3.11)
```
pytest-memray==1.3.0
flaky==3.7.0
```

**Possible Solution**

**Additional context/Screenshots** Add any other context about the problem here. If
applicable, add screenshots to help explain.

**Comment by pablogsal** [comment]
This has been fixed in https://github.com/bloomberg/pytest-memray/pull/50

**Comment by pablogsal** [comment]
Will be available in the next release

**Comment by pablogsal** [comment]
Thanks for the report @graingert !
