### ISSUE TITLE
Changelog links lead to 404

### ISSUE THREAD

**Issue by pquentin** [bloomberg/pytest-memray#66]
## Bug Report

In https://pytest-memray.readthedocs.io/en/latest/news.html, all links to issues are broken because there's a missing s in the URL: it should be issues, not issue, in this line: https://github.com/bloomberg/pytest-memray/blob/38195a67969a62d31c817afaf84222ef831c3bba/docs/conf.py#L30

**Comment by pablogsal** [comment]
@gaborbernat could you take a look if you have some spare cycles?
