### ISSUE TITLE
Release wheel file

### ISSUE THREAD

**Issue by gaborbernat** [bloomberg/pytest-memray#9]
Would avoid need to build a wheel during the installation 👍

**Comment by pablogsal** [comment]
Not sure I follow, we are releasing manylinux 2010 wheels. 🤔

**Comment by pablogsal** [comment]
Ah, good point. We need to hook this to the ci. Want to make a contribution? 🤔😉

**Comment by gaborbernat** [comment]
Sure 👌

**Comment by gaborbernat** [comment]
> Not sure I follow, we are releasing manylinux 2010 wheels. 🤔

Only for memray itself, not pytest-memray.
